create table if not exists public.plans (
  id text primary key,
  group_name text not null,
  category text not null,
  created_by text not null,
  created_at timestamptz not null default now(),
  host_location jsonb not null
);

create table if not exists public.participants (
  id text primary key,
  plan_id text not null references public.plans(id) on delete cascade,
  name text not null,
  joined_at timestamptz not null default now(),
  location jsonb not null
);

create table if not exists public.destinations (
  id bigint generated by default as identity primary key,
  plan_id text not null references public.plans(id) on delete cascade,
  sort_order integer not null default 0,
  place_id text not null,
  name text not null,
  address text not null,
  type text not null,
  lat double precision not null,
  lng double precision not null,
  fairness double precision not null,
  average_distance_km double precision not null,
  distances jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists participants_plan_id_joined_at_idx
  on public.participants (plan_id, joined_at);

create index if not exists destinations_plan_id_sort_order_idx
  on public.destinations (plan_id, sort_order);
