create table if not exists public.plans (
  id text primary key,
  group_name text not null,
  category text not null,
  subcategory text,
  subcategories jsonb not null default '[]'::jsonb,
  created_by text not null,
  created_at timestamptz not null default now(),
  host_location jsonb not null
);

alter table public.plans
  add column if not exists subcategory text,
  add column if not exists subcategories jsonb not null default '[]'::jsonb;

create table if not exists public.participants (
  id text primary key,
  plan_id text not null references public.plans(id) on delete cascade,
  name text not null,
  joined_at timestamptz not null default now(),
  location jsonb not null
);

create table if not exists public.destinations (
  id bigint generated by default as identity primary key,
  plan_id text not null references public.plans(id) on delete cascade,
  sort_order integer not null default 0,
  place_id text not null,
  name text not null,
  address text not null,
  type text not null,
  lat double precision not null,
  lng double precision not null,
  fairness double precision not null,
  average_distance_km double precision not null,
  distances jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.destinations
  add column if not exists rating double precision,
  add column if not exists user_rating_count integer,
  add column if not exists photo_urls jsonb not null default '[]'::jsonb;

create table if not exists public.destination_votes (
  plan_id text not null references public.plans(id) on delete cascade,
  participant_id text not null references public.participants(id) on delete cascade,
  destination_place_id text not null,
  created_at timestamptz not null default now(),
  primary key (plan_id, participant_id)
);

create index if not exists participants_plan_id_joined_at_idx
  on public.participants (plan_id, joined_at);

create index if not exists destinations_plan_id_sort_order_idx
  on public.destinations (plan_id, sort_order);

create index if not exists destination_votes_plan_id_idx
  on public.destination_votes (plan_id, destination_place_id);

create table if not exists public.api_daily_usage (
  service_key text not null,
  usage_date date not null default current_date,
  request_count integer not null default 0,
  primary key (service_key, usage_date)
);

create table if not exists public.api_rate_limits (
  bucket_key text not null,
  window_started_at timestamptz not null,
  request_count integer not null default 0,
  primary key (bucket_key, window_started_at)
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  plan_id text,
  participant_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_event_name_created_at_idx
  on public.analytics_events (event_name, created_at desc);

create index if not exists analytics_events_plan_id_created_at_idx
  on public.analytics_events (plan_id, created_at desc);

create or replace function public.consume_daily_api_quota(service_name text, daily_limit integer)
returns boolean
language plpgsql
as $$
declare
  current_count integer;
begin
  insert into public.api_daily_usage (service_key, usage_date, request_count)
  values (service_name, current_date, 0)
  on conflict (service_key, usage_date) do nothing;

  select request_count
  into current_count
  from public.api_daily_usage
  where service_key = service_name and usage_date = current_date
  for update;

  if current_count >= daily_limit then
    return false;
  end if;

  update public.api_daily_usage
  set request_count = request_count + 1
  where service_key = service_name and usage_date = current_date;

  return true;
end;
$$;

create or replace function public.consume_rate_limit(
  bucket_name text,
  window_seconds integer,
  request_limit integer
)
returns boolean
language plpgsql
as $$
declare
  current_window timestamptz;
  current_count integer;
begin
  current_window :=
    to_timestamp(floor(extract(epoch from now()) / greatest(window_seconds, 1)) * greatest(window_seconds, 1));

  insert into public.api_rate_limits (bucket_key, window_started_at, request_count)
  values (bucket_name, current_window, 0)
  on conflict (bucket_key, window_started_at) do nothing;

  select request_count
  into current_count
  from public.api_rate_limits
  where bucket_key = bucket_name and window_started_at = current_window
  for update;

  if current_count >= request_limit then
    return false;
  end if;

  update public.api_rate_limits
  set request_count = request_count + 1
  where bucket_key = bucket_name and window_started_at = current_window;

  delete from public.api_rate_limits
  where window_started_at < now() - interval '2 hours';

  return true;
end;
$$;
